module.exports = {
  MAIN: "Главная страница",
  SIGNIN: "Вход в аккаунт",
  SIGNUP: "Регистрация",
  PROFILE: 'Профиль',
  CATALOG: "Каталог",
  CATEGORIES: "Категории товаров",
  ABOUT: "О компании",
  DELIVERY: "Доставка",
  DELIVERY_TYPE: "Способ доставки",
  PAYMENT: "Оплата",
  SELECT_PAY: "Способ оплаты",
  GUARANTEE: "Гарантия",
  BASKET: "Корзина",
  CONFIRM_ORDER: "Подтверждение заказа",
};
